## 1. Пример использования матричного умножения в сети с тремя слоями

<img src="img/Backpropagation_1_1.png" width="800" height="800">

### Выходные сигналы второго слоя

Приступим к работе над примером, представленным на этой диаграмме. Входными сигналами нейронной сети являются следующие: 0,9; 0,1 и 0,8. Поэтому входная матрица I имеет следующий вид.

In [11]:
import numpy as np
from scipy import special

In [5]:
I = np.array([[0.9], 
              [0.1], 
              [0.8]])

Как уже было показано, сглаженные комбинированные входные сигналы для этого слоя определяются выражением $X = W -I$, где $I$ — матрица входных сигналов, a $W$ — матрица весов.

In [6]:
w_input_hidden = np.array([[0.9, 0.3, 0.4], 
                           [0.2, 0.8, 0.2], 
                           [0.1, 0.5, 0.6]])

In [7]:
X_hidden = w_input_hidden @ I
X_hidden

array([[1.16],
       [0.42],
       [0.62]])

In [8]:
sigmoid = lambda x: special.expit(x)

In [12]:
X_hsigmoid = sigmoid(X_hidden)
X_hsigmoid

array([[0.76133271],
       [0.60348325],
       [0.65021855]])

### Выходные сигналы третьего слоя слоя

In [13]:
w_hidden_output = np.array([[0.3, 0.7, 0.5], 
                            [0.6, 0.5, 0.2], 
                            [0.8, 0.1, 0.9]])

In [14]:
X_output = w_hidden_output @ X_hsigmoid
X_output

array([[0.97594736],
       [0.88858496],
       [1.25461119]])

In [16]:
X_osigmoid = sigmoid(X_output)
X_osigmoid

array([[0.72630335],
       [0.70859807],
       [0.77809706]])

<img src="img/Backpropagation_1_2.png" width="800" height="800">

## 2. Обратное распространение ошибок

На следующей диаграмме отображена простая сеть с двумя входными узлами, но на этот раз с двумя выходными узлами.

<img src="img/Backpropagation_2_1.png" width="800" height="800">

Ошибка на первом выходном узле обозначена как $e_1$ Не забывайте, что это разность между желаемым значением, предоставляемым тренировочными данными $t_1$ и фактическим выходным значением $o_1$. Таким образом $e_1 = (t_1 - o_1)$. Ошибка на втором выходном узле обозначена как $e_2$.

### Повышаем количество слоев

<img src="img/Backpropagation_2_2.png" width="800" height="800">

Ошибка на первом скрытом узле представляет собой сумму ошибок, распределенных по всем связям, исходящим из этого узла в прямом направлении. На приведенной выше диаграмме показано, что имеется некоторая доля выходной ошибки $e_{\text{выходной, 1}}$ приписываемая связи с весом $w_{11}$, и некоторая доля выходной ошибки $e_{\text{выходной, 2}}$ приписываемая связи с весом $w_{12}$. Вышесказанное можно записать в виде следующего выражения:

$\large e_{\text{скрытый, 1}} = \text{сумма ошибок, распределенных по связям} w_{11} \text{ и } w_{12}$



$\large e_{\text{скрытый, 1}} = e_{\text{выходной, 1}} \cdot \frac{w_{11}}{w_{11} + w_{21}} + e_{\text{выходной, 2}} \cdot \frac{w_{12}}{w_{12} + w_{22}}$

Чтобы проиллюстрировать, как эта теория выглядит на практике, приведем диаграмму, демонстрирующую обратное распространение ошибок в простой трехслойной сети на примере конкретных данных.

<img src="img/Backpropagation_2_3.png" width="800" height="800">

Проследим за обратным распространением одной из ошибок. Вы видите, что после распределения ошибки 0,5 на втором узле выходного слоя между двумя связями с весами 1,0 и 4,0 мы получаем доли, равные 0,1 и 0,4 соответственно. Также можно видеть, что объединенная ошибка на втором узле скрытого слоя представляетсобой сумму распределенных ошибок, в данном случае равных 0,48 и 0,4, сложение которых дает 0,88.

На следующей диаграмме демонстрируется применение той же методики к слою, который предшествует скрытому.

<img src="img/Backpropagation_2_4.png" width="800" height="800">

## 3. Описание обратного распространения ошибок с помощью матричной алгебры