**Задачи для практического задания к уроку 1**

1. Создайте случайный FloatTensor размера 3x4x5
2. Выведите его форму (shape)
3. Приведите его к форме 6х10
4. Создайте случайный IntTensor размера 10
5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти
7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
8. Создайте единичный тензор размера 5x6
9. Переведите его в формат numpy

In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
float_tensor = torch.randn(3, 4, 5).float()
float_tensor

tensor([[[ 0.9851, -1.2953,  1.0926, -1.1445,  1.6767],
         [ 0.8756,  0.0185,  0.0299, -2.2373, -0.4395],
         [ 2.0111,  1.2784,  0.5479,  0.5374,  1.1884],
         [-0.2313, -0.0331,  1.8974, -1.3184, -0.4224]],

        [[ 1.6230, -0.0971, -0.0101,  1.2767, -1.1594],
         [ 0.4946, -1.5093,  0.6165,  2.0378,  1.0296],
         [-0.4164,  0.1368,  1.2391, -1.0944, -0.4602],
         [ 1.2978, -0.2276, -0.4234, -0.4676, -1.4700]],

        [[ 0.7109, -2.4217, -0.3448, -1.3401, -0.7334],
         [-1.4754, -0.1367, -0.7094,  1.4383, -1.3699],
         [-0.7349,  0.9295,  0.9484, -1.1385,  0.6664],
         [-2.0492, -1.1754, -1.8016,  0.1094, -0.0676]]])

In [3]:
# 2. Выведите его форму (shape)
float_tensor.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
float_tensor = float_tensor.reshape(6, 10)
float_tensor.size()

torch.Size([6, 10])

In [5]:
# 4. Создайте случайный IntTensor размера 10
int_tensor = torch.randn(10).int()
int_tensor

tensor([ 0,  0,  0,  0,  0, -1,  0,  0,  1,  0], dtype=torch.int32)

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
float_tensor * int_tensor

tensor([[ 0.0000, -0.0000,  0.0000, -0.0000,  0.0000, -0.8756,  0.0000,  0.0000,
         -2.2373, -0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.2313, -0.0000,  0.0000,
         -1.3184, -0.0000],
        [ 0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.4946, -0.0000,  0.0000,
          2.0378,  0.0000],
        [-0.0000,  0.0000,  0.0000, -0.0000, -0.0000, -1.2978, -0.0000, -0.0000,
         -0.4676, -0.0000],
        [ 0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  1.4754, -0.0000, -0.0000,
          1.4383, -0.0000],
        [-0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  2.0492, -0.0000, -0.0000,
          0.1094, -0.0000]])

In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
mm_tensor = float_tensor.mm(float_tensor.T)
mm_tensor.shape

torch.Size([6, 6])

In [8]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)

y = (x**3) + z - 75 * t
y.backward()
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [9]:
# 8. Создайте единичный тензор размера 5x6
nm_tensor = torch.randn(5, 6)

In [15]:
# 9. Переведите его в формат numpy
nm_tensor.numpy()

array([[-0.6356018 ,  0.7674357 ,  1.2977653 ,  1.5355566 ,  0.41834548,
         1.1885126 ],
       [ 0.5522573 , -0.14125705, -0.68019027,  0.80297494,  0.8723489 ,
         1.1799629 ],
       [ 0.30663657, -0.6124171 , -0.2662205 ,  0.5420237 , -0.4199632 ,
        -1.8126323 ],
       [-0.56907284, -0.5265977 ,  1.0244882 , -1.2007574 , -0.28403944,
         0.71688944],
       [ 0.7075372 , -0.46512887, -0.16157514, -2.0431497 , -0.78299946,
         0.6982327 ]], dtype=float32)