<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [9]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
print(f'a.ndim = {a.ndim} b.ndim = {b.ndim}')
print(f'a.shape = {a.shape} b.shape = {b.shape}\n')
# ========
print(a)
print(b)

a.ndim = 2 b.ndim = 2
a.shape = (100, 100) b.shape = (100, 100)

[[0.47740087 0.81937705 0.96597346 ... 0.14584768 0.31300281 0.99180288]
 [0.85072936 0.97840696 0.84001366 ... 0.06238041 0.23744827 0.3858968 ]
 [0.4582291  0.66025043 0.43751092 ... 0.39940665 0.67562959 0.14791936]
 ...
 [0.75978002 0.90515877 0.460712   ... 0.43684873 0.96309598 0.45141837]
 [0.49371943 0.4603302  0.14018624 ... 0.10758229 0.84435508 0.12170648]
 [0.20893823 0.43748089 0.51117098 ... 0.0172107  0.12800239 0.34233716]]
[[0.10325492 0.82225999 0.86617313 ... 0.32276859 0.07505288 0.37338725]
 [0.56417511 0.66027847 0.28154469 ... 0.67445253 0.64175877 0.1136665 ]
 [0.67840431 0.64821622 0.33737102 ... 0.84272452 0.69564594 0.9804895 ]
 ...
 [0.94142519 0.37376794 0.23078659 ... 0.95483918 0.90368612 0.78512397]
 [0.81365632 0.42702542 0.76753379 ... 0.23265876 0.86956668 0.07397874]
 [0.67229751 0.17000604 0.60118782 ... 0.31486746 0.69842667 0.78347203]]


In [3]:
A = np.array([[1, 3],
              [2, 4]])
B = np.array([[4, 5],
              [6, 7]])
A @ B

array([[22, 26],
       [32, 38]])

In [5]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    size = range(len(a))
    
    return [[sum(a[i][k]*b[k][j] for k in size) for j in size] for i in size]
            

In [8]:
def np_mult(a, b):
    """  
    a: np.array[size, size] --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size] --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return a @ b

In [12]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

Wall time: 4.27 s


In [13]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Wall time: 996 µs


In [14]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [15]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.47918885 0.58045753 0.33151408] [0.77073593 0.18359246 0.28711457]


In [17]:
def scalar_product(a, b):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    return sum(a[i] * b[i] for i in range(len(a)))

In [18]:
def np_scalar_product(a,b):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    return a @ b

In [19]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

Wall time: 0 ns
Wall time: 0 ns


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [29]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    diag = a.diagonal()
    return diag[diag % 2 == 0].sum()

In [4]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[4, 8, 4, 6, 8],
       [8, 1, 4, 9, 6],
       [3, 3, 8, 6, 7],
       [5, 2, 6, 5, 3],
       [9, 8, 4, 2, 6]])

In [31]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

Wall time: 1min 28s


10

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [18]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column] --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    
    return np.cumsum(A, axis=1)

In [19]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = sps.uniform.rvs(size=(50, 1000))
%time S2 = cumsum(A)

Wall time: 0 ns


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [39]:
from copy import copy
def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    Y = np.copy(X)
    Y[:,1::2] = a
    Y[:,0::2] **= 3
    return np.hstack((X, Y[:,::-1]))

In [40]:
X = np.array([[i for i in range(1, 1000000, 2)]])
%time S2 = np_transformation(X, 5)

Wall time: 3.01 ms


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [42]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    is_new_in_row = np.array(a[1:] != a[:-1])
    position = np.append(np.where(is_new_in_row), len(a) - 1)
    lengths = np.diff(np.append(-1, position))
    return (a[position], lengths)

In [31]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [43]:
%%timeit -n 1000
x, num = np_encode(X)

16 µs ± 3.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [40]:
def encode(a):
    mask = np.r_[True, a[:-1]!=a[1:], True]
    counts = np.diff(np.flatnonzero(mask))
    return (a[mask[:-1]], counts)

In [41]:
%%timeit -n 1000
x, num = np_encode(X)

14.3 µs ± 972 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
